In [8]:
import pandas as pd
import geopandas as gpd

In [9]:
race_geo = gpd.read_file('../data/davidson_race_by_tract/davidson_race_by_tract.geojson')

In [10]:
race_geo.head()

,geoid,name,B02001001,"B02001001, Error",B02001002,"B02001002, Error",B02001003,"B02001003, Error",B02001004,"B02001004, Error",...,"B02001006, Error",B02001007,"B02001007, Error",B02001008,"B02001008, Error",B02001009,"B02001009, Error",B02001010,"B02001010, Error",geometry
0,01000US,United States,324697795.0,0.0,235377662.0,54551.0,41234642.0,32548.0,2750143.0,13011.0,...,4711.0,16047369.0,97264.0,10763902.0,107388.0,1625998.0,28610.0,9137904.0,82541.0,"MULTIPOLYGON (((-168.22527 -14.53591, -168.199..."
1,04000US47,Tennessee,6709356.0,0.0,5205132.0,4583.0,1124473.0,3575.0,18189.0,1047.0,...,491.0,92655.0,4252.0,147536.0,3695.0,12138.0,1160.0,135398.0,3482.0,"MULTIPOLYGON (((-82.22206 36.15696, -82.22214 ..."
2,05000US47037,"Davidson County, TN",687488.0,0.0,440299.0,1694.0,186295.0,1403.0,1534.0,404.0,...,140.0,16136.0,1796.0,17947.0,1444.0,1540.0,408.0,16407.0,1432.0,"MULTIPOLYGON (((-86.98361 36.20957, -86.98398 ..."
3,14000US47037010103,"Census Tract 101.03, Davidson, TN",2533.0,191.0,2457.0,201.0,7.0,10.0,8.0,14.0,...,12.0,0.0,12.0,45.0,42.0,0.0,12.0,45.0,42.0,"MULTIPOLYGON (((-86.91752 36.33976, -86.91747 ..."
4,14000US47037010104,"Census Tract 101.04, Davidson, TN",2955.0,279.0,2713.0,268.0,167.0,136.0,16.0,25.0,...,11.0,0.0,12.0,40.0,42.0,22.0,33.0,18.0,24.0,"MULTIPOLYGON (((-86.97440 36.24991, -86.97244 ..."

In [11]:
davidson_w_b = race_geo[['geoid', 'name', 'B02001001', 'B02001001, Error', 'B02001002', 'B02001002, Error', 'B02001003', 'B02001003, Error', 'geometry']]

In [12]:
davidson_w_b.head()

,geoid,name,B02001001,"B02001001, Error",B02001002,"B02001002, Error",B02001003,"B02001003, Error",geometry
0,01000US,United States,324697795.0,0.0,235377662.0,54551.0,41234642.0,32548.0,"MULTIPOLYGON (((-168.22527 -14.53591, -168.199..."
1,04000US47,Tennessee,6709356.0,0.0,5205132.0,4583.0,1124473.0,3575.0,"MULTIPOLYGON (((-82.22206 36.15696, -82.22214 ..."
2,05000US47037,"Davidson County, TN",687488.0,0.0,440299.0,1694.0,186295.0,1403.0,"MULTIPOLYGON (((-86.98361 36.20957, -86.98398 ..."
3,14000US47037010103,"Census Tract 101.03, Davidson, TN",2533.0,191.0,2457.0,201.0,7.0,10.0,"MULTIPOLYGON (((-86.91752 36.33976, -86.91747 ..."
4,14000US47037010104,"Census Tract 101.04, Davidson, TN",2955.0,279.0,2713.0,268.0,167.0,136.0,"MULTIPOLYGON (((-86.97440 36.24991, -86.97244 ..."

In [13]:
davidson_w_b.rename(columns={'B02001001': 'total_pop', 'B02001001, Error': 'total_pop_MOE', 'B02001002': 'white_alone', 'B02001002, Error': 'white_alone_MOE', 'B02001003': 'black_africanamerican_alone', 'B02001003, Error': 'black_africanamerican_alone_MOE'}, inplace=True)

C:\Users\16159\anaconda3\envs\geospatial\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [14]:
davidson_w_b

,geoid,name,total_pop,total_pop_MOE,white_alone,white_alone_MOE,black_africanamerican_alone,black_africanamerican_alone_MOE,geometry
0,01000US,United States,324697795.0,0.0,235377662.0,54551.0,41234642.0,32548.0,"MULTIPOLYGON (((-168.22527 -14.53591, -168.199..."
1,04000US47,Tennessee,6709356.0,0.0,5205132.0,4583.0,1124473.0,3575.0,"MULTIPOLYGON (((-82.22206 36.15696, -82.22214 ..."
2,05000US47037,"Davidson County, TN",687488.0,0.0,440299.0,1694.0,186295.0,1403.0,"MULTIPOLYGON (((-86.98361 36.20957, -86.98398 ..."
3,14000US47037010103,"Census Tract 101.03, Davidson, TN",2533.0,191.0,2457.0,201.0,7.0,10.0,"MULTIPOLYGON (((-86.91752 36.33976, -86.91747 ..."
4,14000US47037010104,"Census Tract 101.04, Davidson, TN",2955.0,279.0,2713.0,268.0,167.0,136.0,"MULTIPOLYGON (((-86.97440 36.24991, -86.97244 ..."
...,...,...,...,...,...,...,...,...,...
159,14000US47037019400,"Census Tract 194, Davidson, TN",5810.0,569.0,3891.0,444.0,1578.0,308.0,"MULTIPOLYGON (((-86.80102 36.17745, -86.80100 ..."
160,14000US47037019500,"Census Tract 195, Davidson, TN",7956.0,795.0,6388.0,698.0,849.0,285.0,"MULTIPOLYGON (((-86.80272 36.15248, -86.80084 ..."
161,14000US47037019600,"Census Tract 196, Davidson, TN",3843.0,480.0,2768.0,478.0,545.0,411.0,"MULTIPOLYGON (((-86.76398 36.15376, -86.76368 ..."
162,14000US47037980100,"Census Tract 9801, Davidson, TN",0.0,12.0,0.0,12.0,0.0,12.0,"MULTIPOLYGON (((-86.70035 36.11833, -86.70019 ..."
163,14000US47037980200,"Census Tract 9802, Davidson, TN",0.0,12.0,0.0,12.0,0.0,12.0,"MULTIPOLYGON (((-86.77105 36.11113, -86.77099 ..."

In [16]:
davidson_w_b.to_file('../data/davidson_race_by_tract/davidson_race_by_tract_clean.geojson')